### ISSUE TITLE
Unit test framework will not run

### ISSUE THREAD

**Issue by lod** [zookeepr/zookeepr#379]
Attempting to run zookeepr unit tests results in failures, I believe these originate from inside the test framework setup.

The error line inside `zkpylons/tests/__init__.py` has two options, suggesting that this has been an issue in the past. Both options result in an error.
```
  SetupCommand('setup-app').run([config['__file__']])
  #SetupCommand('setup-app').run([pylons.test.pylonsapp.config['__file__']])
```
Testing performed on 52.64.14.135 test host inside virtual environment:

```
(env)zookeepr@ip-172-31-5-84 ~/z/zkpylons> nosetests

  EE
    ======================================================================
  ERROR: test suite for <module 'zkpylons.model' from '/home/zookeepr/zookeepr/zkpylons/model  /__init__.py'>
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 209, in run
      self.setUp()
    File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 292, in setUp
      self.setupContext(ancestor)
    File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 315, in setupContext
      try_run(context, names)
    File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/util.py", line 469, in try_run
      return func(obj)
    File "/home/zookeepr/zookeepr/zkpylons/model/__init__.py", line 86, in setup
      role.setup(meta)
    File "/home/zookeepr/zookeepr/zkpylons/model/role.py", line 9, in setup
      meta.Session.add_all(
  AttributeError: 'module' object has no attribute 'Session'
  
  ======================================================================
  ERROR: Failure: KeyError ('__file__')
  ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/zookeepr/zookeepr/zkpylons/tests/__init__.py", line 23, in <module>
    SetupCommand('setup-app').run([config['__file__']])
  File "/home/zookeepr/zookeepr/env/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/registry.py", line 146, in __getitem__
    return self._current_obj()[key]
KeyError: '__file__'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=2)

  ==================
  =  Swapped setup line  =
  ==================


EE
======================================================================
ERROR: test suite for <module 'zkpylons.model' from '/home/zookeepr/zookeepr/zkpylons/model/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/util.py", line 469, in try_run
    return func(obj)
  File "/home/zookeepr/zookeepr/zkpylons/model/__init__.py", line 86, in setup
    role.setup(meta)
  File "/home/zookeepr/zookeepr/zkpylons/model/role.py", line 9, in setup
    meta.Session.add_all(
AttributeError: 'module' object has no attribute 'Session'

======================================================================
ERROR: Failure: AttributeError ('NoneType' object has no attribute 'config')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/zookeepr/zookeepr/env/local/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/zookeepr/zookeepr/zkpylons/tests/__init__.py", line 24, in <module>
    SetupCommand('setup-app').run([pylons.test.pylonsapp.config['__file__']])
AttributeError: 'NoneType' object has no attribute 'config'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=2)
```

**Comment by lod** [comment]
Closed by #420
